#!/usr/bin/env bash

die()
{
  echo >&2 '!!! ERROR: $*'
  exit 1
}

cd "$(dirname "$0")"
rm -f small.zim
zimwriterfs -w main.html \
            -f favicon.png \
            -l=en \
            -t="Test ZIM file" \
            -d="" \
            -c="" \
            -p="" \
            small_zimfile_data \
            small.zim \
&& echo 'small.zim was successfully created' \
|| die 'Failed to create small.zim'

head -c40 small.zim > invalid.smaller_than_header.zim \
  || die 'Failed to create invalid.smaller_than_header.zim'
