freebsd_instance:
  image: freebsd-12-2-release-amd64

task:
  install_script:
  - pkg update -f
  - pkg upgrade -fy
  - pkg install -y meson ninja pkgconf python icu xapian-core zstd git
  script: |
    mkdir _build
    env CFLAGS="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing" meson --prefix /usr/local  --mandir man  --infodir share/info --buildtype release  --strip -Dctpp2-install-prefix=/usr/local _build .
    cd _build
    ninja
