codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 90%

ignore:
  - "test"
  - "examples"
